import datetime
import re
from pathlib import Path

from aether_scientist.agent.state import ResearchState


def _validate_citations(text: str, n_sources: int) -> str:
    """Validate citations against available sources, stripping out-of-bounds ones."""

    def _replace(match: re.Match[str]) -> str:
        idx = int(match.group(1))
        if 1 <= idx <= n_sources:
            return match.group(0)
        return ""

    cleaned = re.sub(r"\[(\d+)\]", _replace, text)
    return re.sub(r"\s{2,}", " ", cleaned).strip()


def render_report(
    question: str,
    state: ResearchState,
    confidence: float | None = None,
    profile: str | None = None,
    device: str = "cpu",
) -> str:
    """Render a structured, cited Markdown research report from agent state."""
    conf = confidence if confidence is not None else 0.0
    prof = profile or state.profile
    date_str = datetime.date.today().isoformat()
    n_sources = len(state.sources)

    exec_sentences: list[str] = []
    unanswered: list[str] = []
    findings_blocks: list[str] = []

    for f in state.findings:
        sq = f.get("sub_query", "")
        raw_text = f.get("text", "").strip()
        cleaned_text = _validate_citations(raw_text, n_sources)

        if "insufficient evidence" in cleaned_text.lower():
            unanswered.append(sq)
        else:
            first_sentence = cleaned_text.split(". ")[0].strip()
            if first_sentence:
                if not first_sentence.endswith("."):
                    first_sentence += "."
                exec_sentences.append(first_sentence)

        findings_blocks.append(f"### {sq}\n{cleaned_text}")

    if exec_sentences:
        summary_text = " ".join(exec_sentences[:3])
    else:
        summary_text = (
            "Insufficient evidence was identified in the indexed corpus "
            "to answer the research inquiry."
        )

    cov = state.coverage()
    unanswered_str = ", ".join(unanswered) if unanswered else "none"

    ref_lines: list[str] = []
    for s in state.sources:
        idx = s.get("index", 1)
        title = s.get("title", "Document")
        source = s.get("source", "")
        chunk_id = s.get("chunk_id", 0)
        score = s.get("score", 0.0)
        ref_lines.append(f"[{idx}] {title} — {source}, chunk_{chunk_id} (score {score:.2f})")

    refs_block = "\n".join(ref_lines) if ref_lines else "*No sources referenced.*"
    findings_joined = (
        "\n\n".join(findings_blocks) if findings_blocks else "*No findings generated.*"
    )

    return (
        f"# Research Report: {question}\n"
        f"*Generated by AetherScientist ({prof}, {date_str}, device: {device}) — "
        f"confidence: {conf:.2f}*\n\n"
        f"## Executive Summary\n{summary_text}\n\n"
        f"## Key Findings\n{findings_joined}\n\n"
        f"## Coverage & Limitations\n"
        f"- Sources: {cov['n_sources']} chunks from {cov['n_docs']} documents "
        f"(mean score {cov['mean_score']:.2f})\n"
        f"- Unanswered sub-queries: {unanswered_str}\n\n"
        f"## References\n{refs_block}\n"
    )


def write_report(md: str, path: Path | str) -> Path:
    """Write markdown report content to destination file path."""
    dest = Path(path)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(md, encoding="utf-8")
    return dest
